project_id = "mhsxbmugaoqfuqqiqbta"

[functions.calcular-frete]
verify_jwt = false

[functions.pagbank-checkout]
verify_jwt = false

[functions.pagbank-webhook]
verify_jwt = false

[functions.melhor-envio-enviar]
verify_jwt = false

[functions.admin-orders]
verify_jwt = false

[functions.pagbank-order]
verify_jwt = false

[functions.pagbank-order-status]
verify_jwt = false
